#game window constants
ROWS = 15
COLS = 15
TILE_SIZE = 48
COMMANDLINE_PANEL = 350
SCREEN_WIDTH = TILE_SIZE * COLS
SCREEN_HEIGHT = TILE_SIZE * ROWS
FPS = 60
HEALTH = 100
MONEY = 1000

#enemy constants
SPAWN_COOLDOWN = 400

#turret constanst
ANIMATION_STEPS = 8
ANIMATION_DELAY = 15
KILL_REWARD = 5